# -*- coding: utf-8 -*-
"""echo_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xr0Q9CTW3XkCiwEEeeBSX9K4VwF1GEGj
"""

import gpiod
import time

TRIG_LINE = 216   # GPIO09 핀
ECHO_LINE = 194   # GPIO12 핀

chip = gpiod.chip('gpiochip0')
trig = chip.get_line(TRIG_LINE)
echo = chip.get_line(ECHO_LINE)

req_out = gpiod.line_request()
req_out.consumer = 'trig'
req_out.request_type = gpiod.line_request.DIRECTION_OUTPUT

req_in = gpiod.line_request()
req_in.consumer = 'echo'
req_in.request_type = gpiod.line_request.DIRECTION_INPUT

trig.request(req_out)
echo.request(req_in)

try:
	while True:
    	trig.set_value(0)
    	time.sleep(0.00001)
    	trig.set_value(1)
    	time.sleep(0.00001)
    	trig.set_value(0)

    	while echo.get_value() == 0:
        	t0 = time.time()
    	while echo.get_value() == 1:
        	t1 = time.time()

    	distance = (t1 - t0) * 17000
    	print(f'거리: {distance:.0f} cm')
    	time.sleep(0.5)

except KeyboardInterrupt:
	trig.release()
	echo.release()